### ISSUE TITLE
[MC][AsmParser] Parse instruction modifiers

### ISSUE THREAD

**Issue by asl** [matter-labs/era-compiler-llvm#416]
- [x] `set_flags`
 - [x] predicates
 - [x] swap

Spec:
 - https://matter-labs.github.io/eravm-spec/spec.html#Modifiers
 - https://matter-labs.github.io/eravm-spec/spec.html#predication

**Comment by atrosinenko** [comment]
Works, assuming the only permitted syntax is `mnemonic[.s][!][.cond]`, in this particular order, without whitespace in between `mnemonic` and `.s`. Whitespace is accepted around `!` and before `.cond`.

The conditional codes supported are listed in the `arith-modifiers.s` test file.

**Comment by asl** [comment]
> Whitespace is accepted around ! and before .cond.

Is this a desired feature?

**Comment by akiramenai** [comment]
> Is this a desired feature?

I'd say no.

**Comment by atrosinenko** [comment]
For arithmetic instructions, `name[.s][!][.cond]` syntax is supported
* the three optional modifiers should be in this particular order
* without spaces in between (i.e. `sub.s  ! r1, r2, r3` is rejected due to space before `!`)
* with optional `.s` modifier not supported for commutative instructions as there are no corresponding opcodes defined
* currently, multiple names are accepted for each condition code (such as `.le` and `.if_le`) - these are tracked in a separate issue: #440 

Tests (links to the HEAD of `era-vm/asm-parser` branch):
* [`arith-modifiers.s`](https://github.com/matter-labs/compiler-llvm/blob/eravm-mc/asm-parser/llvm/test/MC/EraVM/asm-parser/arith-modifiers.s)
* [`mnemonic-errors.s`](https://github.com/matter-labs/compiler-llvm/blob/eravm-mc/asm-parser/llvm/test/MC/EraVM/asm-parser/mnemonic-errors.s)
* for non-arithmetic instructions, `.s` (only applicable to pointer modification instructions) and condition codes are tested alongside corresponding instructions
