### ISSUE TITLE
[MC][AsmParser] Parse heap manipulation instructions

### ISSUE THREAD

**Issue by asl** [matter-labs/era-compiler-llvm#419]
- [x] `uma.fat_ptr_read in1, out` aliased as `ld in1, out`
 - [x] `uma.fat_ptr_read.inc in1, out` aliased as `ld.inc in1, out`
 - [x] `uma.heap_read in1, out` aliased as `ld.1 in1, out`
 - [x] `uma.aux_heap_read in1, out` aliased as `ld.2 in1, out`
 - [x] `uma.inc.heap_read in1, out1, out2` aliased as `ld.1.inc in1, out1, out2`
 - [x] `uma.inc.aux_heap_read in1, out1, out2` aliased as `ld.2.inc in1, out1, out2`
 - [x] `uma.heap_write in1, in2` aliased as `st.1.inc in1, out`
 - [x] `uma.aux_heap_write in1, in2` aliased as `st.2.inc in1, out`
 - [x] `uma.inc.heap_write in1, in2` aliased as `st.1.inc in1, out`
 - [x] `uma.inc.aux_heap_write in1, in2` aliased as `st.2.inc in1, out`

Spec:
 - https://matter-labs.github.io/eravm-spec/spec.html#LoadPtrDefinition
 - https://matter-labs.github.io/eravm-spec/spec.html#LoadPtrIncDefinition
 - https://matter-labs.github.io/eravm-spec/spec.html#LoadDefinition
 - https://matter-labs.github.io/eravm-spec/spec.html#LoadIncDefinition
 - https://matter-labs.github.io/eravm-spec/spec.html#StoreDefinition
 - https://matter-labs.github.io/eravm-spec/spec.html#StoreIncDefinition

**Comment by atrosinenko** [comment]
Probably, incorrect aliases in https://matter-labs.github.io/eravm-spec/spec.html#StoreDefinition (non-incrementing `uma.*_write` to `st.*.inc` instructions):

```
    uma.heap_write in1, in2 aliased as st.1.inc in1, out
    uma.aux_heap_write in1, in2 aliased as st.2.inc in1, out
```

**Comment by atrosinenko** [comment]
Aside from this, [Store](https://matter-labs.github.io/eravm-spec/spec.html#StoreDefinition) and [StoreInc](https://matter-labs.github.io/eravm-spec/spec.html#StoreIncDefinition) have the following definitions:

```
Abstract Syntax: OpStore (ptr: in_regimm) (val: in_reg) (mem:data_page_type) (swap: mod_swap)
Assembly:
    uma.heap_write in1, in2 aliased as st.1.inc in1, out
    uma.aux_heap_write in1, in2 aliased as st.2.inc in1, out

Abstract Syntax: OpStoreInc (ptr: in_regimm) (val: in_reg) (mem:data_page_type) (inc_ptr: out_reg) (swap: mod_swap)
Assembly:
    uma.inc.heap_write in1, in2 aliased as st.1.inc in1, out
    uma.inc.aux_heap_write in1, in2 aliased as st.2.inc in1, out
```

In both cases, the shorter instruction should probably have "in1, in2" operands instead of "in1, out". Additionally, the `*Inc` versions have an output pointer operand in their abstract syntax. Whether input and output register should be the same in case of `fat_ptr_read`, is more about binary encoding. But load/store instructions operating on the "local" heap have their first operand of type [`in_regimm`](https://matter-labs.github.io/eravm-spec/spec.html#in_regimm), so for the "imm" case there is no "default" register to write the incremented pointer to. [LoadInc](https://matter-labs.github.io/eravm-spec/spec.html#LoadIncDefinition) explicitly mentions the second output operand in its assembly syntax. [StoreInc](https://matter-labs.github.io/eravm-spec/spec.html#StoreIncDefinition) should probably have the additional output operand as well ("in1, in2, out")

**Comment by atrosinenko** [comment]
Missing features:
- [x] `ld.inc` (`uma.fat_ptr_read.inc`)
- [x] pointer-incrementing versions of local heap load/store if the first operand is immediate (permitted by the spec)

**Comment by atrosinenko** [comment]
Works, but an extra output (incremented pointer) was added to the following instructions:
* `ld.inc` (technically, could be tied output?)
* `st.1.inc` / `st.2.inc` (the first operand is `in_regimm`, so cannot be tied)

Tests (links to the HEAD of `era-vm/asm-parser` branch):
* [`uma.s`](https://github.com/matter-labs/compiler-llvm/blob/eravm-mc/asm-parser/llvm/test/MC/EraVM/asm-parser/uma.s)

Note that [StoreDefinition](https://matter-labs.github.io/eravm-spec/spec.html#StoreDefinition) mistakenly mentions `.inc` versions of the mnemonics.
