### ISSUE TITLE
[META][MC] Support new / updated instructions from 1.5 ISA

### ISSUE THREAD

**Issue by asl** [matter-labs/era-compiler-llvm#444]
From 1.6 ISA spec by @sayon 

- [x] #453
- [x] #455
- [x] #456
- [x] #457
- [x] #458
- [x] #441

**Comment by asl** [comment]
The updated spec is at https://matter-labs.github.io/eravm-spec/spec.html#asm_instruction

**Comment by atrosinenko** [comment]
@sayon @akiramenai @hedgar2017 [`asm_instruction`](https://matter-labs.github.io/eravm-spec/spec.html#asm_instruction) definition in the spec mentions a number of instructions:
* `OpContextSetErgsPerPubdataByte` was removed in 1.5.0 - should it be completely removed from the MC layer or is some kind of compatibility with pre-1.5.0 ISA expected (such as disassembling machine code)
* the asm syntax for `OpIncrementTxNumber` was defined by previous version of the spec (with `context.inc_tx_num` mnemonic) but not by the current one - what mnemonic to use in the new asm syntax?
* the asm syntax for `OpAuxMutating` is not defined neither now nor before - should it be ignored for now?

**Comment by atrosinenko** [comment]
@sayon The new spec on [`OpLoad`](https://matter-labs.github.io/eravm-spec/spec.html#LoadDefinition) lists the following variants of syntax:
```
    ldm in1, out1
    ldm.h to access heap (default)
    ldm.ah to access auxheap
    ldm.st to access static memory page
```
If `ldm in1, out1` and `ldm.h in1, out1` are aliases, which should be used by default (that is, for printing) or is `ldm in1, out1` line (no modifiers at all) provided for illustration purpose only and should be rejected by the parser?

**Comment by sayon** [comment]
0. Note: this is for VM 1.5, not 1.6. 1.6 will come in more distant future. 

>OpContextSetErgsPerPubdataByte was removed in 1.5.0 - should it be completely removed from the MC layer or is some kind of compatibility with pre-1.5.0 ISA expected (such as disassembling machine code)

This instruction is not replaced with anything, just removed, and there is a placeholder instead in the VM code called smth like `AuxMutating0`. My vote is for leaving it in the ISA but emitting a legacy warning when trying to compile a code with it.  The mnemonic is `stpub`.


> the asm syntax for OpIncrementTxNumber was defined by previous version of the spec (with context.inc_tx_num mnemonic) but not by the current one - what mnemonic to use in the new asm syntax?

Thank you, this was not intentional. The mnemonic is`inctx`, i will restore it in the next iteration.


> the asm syntax for OpAuxMutating is not defined neither now nor before - should it be ignored for now?

Yes, please ignore as it is a placeholder. This was not clear in the moment when spec was written.


As for the default modifiers, I think here is what we can do, universally (@akiramenai @hedgar2017 correct me if you disagree):

1. For printing, be maximally explicit, include all modifiers that make sense. Therefore, `ldm.h` for printing.
2. ~~Accept both `ldm` and `ldm.h`.~~ accept only `ldm.h` (edit)

I see it as an instance of the "in module interfaces, be relaxed on inputs, strict on the outputs" system design principle.

**Comment by hedgar2017** [comment]
@sayon @atrosinenko please be restrictive on inputs as well.
E.g. the main heap isn't such a default memory page to make its modifier a default.

**Comment by sayon** [comment]
In this case


1. For printing, be maximally explicit, include all modifiers that make sense. Therefore, ldm.h for printing.
2. For parsing, accept `ldm.h` but not `ldm`.

**Comment by atrosinenko** [comment]
Mentioned printing warning for `stpub` instruction in #577. All other comments are to the best of my knowledge accounted for in #576.
