### ISSUE TITLE
[ELF] Properly handle relocations

### ISSUE THREAD

**Issue by asl** [matter-labs/era-compiler-llvm#452]

**Comment by atrosinenko** [comment]
At least we need a relocation to write absolute `code` and `stack` addresses to uint16 immediate operands of instructions. At now, `R_ERAVM_16` is used for such purpose. According to [addressing modes description](https://matter-labs.github.io/eravm-spec/spec.html#Addressing) from the spec, only multiples of 32 bytes should be accepted and the offset written should be divided by 32:
```
.rodata + 128 -> 4 (as big-endian uint16)
.data + 123   -> 4 (as big-endian uint16)
.rodata + 1 - error
.data + 1   - error
```

**Comment by atrosinenko** [comment]
At now, there are two relocation types emitted by the backend:
* `R_ERAVM_16_SCALE_32` for code (actually, const) and stack operands of arithmetic instructions. These operands refer to code and stack pages interpreted as an array of 32-byte words.
  - Semantics: take the address associated with the relocation, divide it by 32 (emit error if not divisible). Then add the resulting value to the contents of 16 bit big-endian _place_.
* `R_ERAVM_16_SCALE_8` for encoding jump targets. These operands refer to instruction indexes, the size of an instruction is 8 bytes.
  - Semantics: the same as  `R_ERAVM_16_SCALE_32` with divisor being 8 instead of 32.

Presently, the disassembler itself ignores relocations and `llvm-objdump` prints them if `-r` option is passed:
```
$ cat /tmp/data.s
  .data
dummy:
  .cell 42
  .globl array
array:
  .cell 1
  .cell 2
  .cell 3

  .text
foo:
  add stack[@array + 1], r0, r1
  ret
$ ./bin/llvm-mc -arch=eravm -filetype=obj -o /tmp/data.o < /tmp/data.s
$ ./bin/llvm-objdump -dr /tmp/data.o 

/tmp/data.o:    file format elf32-eravm

Disassembly of section .text:

00000000 <foo>:
       0: 00 00 00 01 01 00 00 31       add     stack[1 + r0], r0, r1
                        00000002:  R_ERAVM_16_SCALE_32  array
       8: 00 00 00 00 00 01 04 2d       ret
```
In the above example the relocation is to be interpreted as:
* compute `address(array) / 32` which is `1`
* add 1 to the value in the Imm0 field of the instruction (which is 1), write the result (2) there

**Comment by atrosinenko** [comment]
Opened #586 for discussing possible improvements to disassembling relocations and #587 for missing negative test.
