### ISSUE TITLE
Implement SpAdd / SpSub

### ISSUE THREAD

**Issue by asl** [matter-labs/era-compiler-llvm#453]
Spec: 
  - https://matter-labs.github.io/eravm-spec/spec.html#SpAddDefinition
  - https://matter-labs.github.io/eravm-spec/spec.html#SpSubDefinition

**Comment by atrosinenko** [comment]
This ultimately depends on how to model NOP opcodes in the backend: #483

**Comment by atrosinenko** [comment]
Currently, there are `InstAlias`es defined for incrementing and decrementing SP (such `nop stack+=[1]` instead of `nop r0, r0, stack+=[1]`). In #576 these aliases are updated according to the new specification (see #483 for discussion).

Supporting `incsp reg+imm` syntax required updating asm parser - only `reg`, `imm` and `reg+imm` forms are implemented in #576 so far (i.e. no `imm+reg` syntax).

**Comment by atrosinenko** [comment]
In #576, the three forms of `incsp` and `decsp` are defined (as per the specification):
```
incsp reg+imm
incsp reg
incsp imm
```
Closing the issue for now. Please reopen if it is implied that both `reg+imm` and `imm+reg` syntax should be accepted interchangeably.
