### ISSUE TITLE
[MC] Refine Near / Far Ret / Revert / Panic

### ISSUE THREAD

**Issue by asl** [matter-labs/era-compiler-llvm#455]

**Comment by asl** [comment]
@atrosinenko Is this done?

**Comment by atrosinenko** [comment]
On tablegen description, a few cleanups are possible (most obvious is removing the `InstAlias<"panic${cc}", (PANIC pred:$cc)>` alias that is not needed anymore) and the following pseudo looks suspicious
```
let isReturn = 1, isTerminator = 1, isBarrier = 1  in {
def RET  : Pseudo<(outs), (ins pred:$cc), [(EraVMret)]>,
           PseudoInstExpansion<(RETr R1, pred:$cc)>;
}
```
as it cannot be replaced by `Pat<...>` because `R1` is not required to be alive right after ISel at this point of basic block (and is actually unused).

On user-facing behavior, in #567 there was discussed the preferred way to handle `to_label` versions. The only remaining question (aside from renaming the mnemonics) is whether to keep `ret` and `rev` as aliases for `ret r1` and `rev r1`. They are not mentioned in the updated spec but at least the first one seems useful in almost any function.

**Comment by atrosinenko** [comment]
@sayon As far as I know, it was decided to keep `ret` and `rev` aliases of `ret r1` and `rev r1`, correspondingly. These aliases are already handled by the MC layer (and updated in #576 as needed).
